linters:
  enable-all: true
  disable:
    # Long line lengths are a presentation issue.
    - lll
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/grafana/killercoda/tools/transformer/extract
          - github.com/grafana/killercoda/tools/transformer/killercoda
          - github.com/grafana/killercoda/tools/transformer/parser
          - github.com/yuin/goldmark
          - github.com/yuin/goldmark-meta
          - github.com/yuin/goldmark/extension
          - github.com/yuin/goldmark/parser
          - github.com/yuin/goldmark/renderer/html
          - github.com/yuin/goldmark/text
          - mvdan.cc/xurls/v2
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - NodeRenderer
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
  varnamelen:
    ignore-names:
    - err
    - fi
    # Common name for File variables.
    - f
    # Common names for iterator variables.
    - i
    - j
    # Common name for test cases.
    - tc
    # Common name for io.Writer.
    - w
