// Code generated by "generate-directives"; DO NOT EDIT.

package main

const (
	finishStartMarker     = `<!-- INTERACTIVE finish START -->`
	finishEndMarker       = `<!-- INTERACTIVE finish END -->`
	ignoreStartMarker     = `<!-- INTERACTIVE ignore START -->`
	ignoreEndMarker       = `<!-- INTERACTIVE ignore END -->`
	includeStartMarker    = `<!-- INTERACTIVE include START -->`
	includeEndMarker      = `<!-- INTERACTIVE include END -->`
	introStartMarker      = `<!-- INTERACTIVE intro START -->`
	introEndMarker        = `<!-- INTERACTIVE intro END -->`
	pageIntroStartMarker  = `<!-- INTERACTIVE page intro.md START -->`
	pageIntroEndMarker    = `<!-- INTERACTIVE page intro.md END -->`
	pageFinishStartMarker = `<!-- INTERACTIVE page finish.md START -->`
	pageFinishEndMarker   = `<!-- INTERACTIVE page finish.md END -->`
	copyStartMarker       = `<!-- INTERACTIVE copy START -->`
	copyEndMarker         = `<!-- INTERACTIVE copy END -->`
	execStartMarker       = `<!-- INTERACTIVE exec START -->`
	execEndMarker         = `<!-- INTERACTIVE exec END -->`
)

var pageStepStartMarkers = [20]string{
	"<!-- INTERACTIVE page step1.md START -->",
	"<!-- INTERACTIVE page step2.md START -->",
	"<!-- INTERACTIVE page step3.md START -->",
	"<!-- INTERACTIVE page step4.md START -->",
	"<!-- INTERACTIVE page step5.md START -->",
	"<!-- INTERACTIVE page step6.md START -->",
	"<!-- INTERACTIVE page step7.md START -->",
	"<!-- INTERACTIVE page step8.md START -->",
	"<!-- INTERACTIVE page step9.md START -->",
	"<!-- INTERACTIVE page step10.md START -->",
	"<!-- INTERACTIVE page step11.md START -->",
	"<!-- INTERACTIVE page step12.md START -->",
	"<!-- INTERACTIVE page step13.md START -->",
	"<!-- INTERACTIVE page step14.md START -->",
	"<!-- INTERACTIVE page step15.md START -->",
	"<!-- INTERACTIVE page step16.md START -->",
	"<!-- INTERACTIVE page step17.md START -->",
	"<!-- INTERACTIVE page step18.md START -->",
	"<!-- INTERACTIVE page step19.md START -->",
}
var pageStepEndMarkers = [20]string{
	"<!-- INTERACTIVE page step1.md END -->",
	"<!-- INTERACTIVE page step2.md END -->",
	"<!-- INTERACTIVE page step3.md END -->",
	"<!-- INTERACTIVE page step4.md END -->",
	"<!-- INTERACTIVE page step5.md END -->",
	"<!-- INTERACTIVE page step6.md END -->",
	"<!-- INTERACTIVE page step7.md END -->",
	"<!-- INTERACTIVE page step8.md END -->",
	"<!-- INTERACTIVE page step9.md END -->",
	"<!-- INTERACTIVE page step10.md END -->",
	"<!-- INTERACTIVE page step11.md END -->",
	"<!-- INTERACTIVE page step12.md END -->",
	"<!-- INTERACTIVE page step13.md END -->",
	"<!-- INTERACTIVE page step14.md END -->",
	"<!-- INTERACTIVE page step15.md END -->",
	"<!-- INTERACTIVE page step16.md END -->",
	"<!-- INTERACTIVE page step17.md END -->",
	"<!-- INTERACTIVE page step18.md END -->",
	"<!-- INTERACTIVE page step19.md END -->",
}
