version: "3.7"

x-name: &compose-project-name simple-lgtm

services:

  lgtm:
    container_name: lgtm
    image: grafana/otel-lgtm
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3000:3000"
      - "3017:4317"
      - "3018:4318"
    restart: unless-stopped

  alloy:
    container_name: alloy
    image: grafana/alloy:v1.9.0
    ports:
      - "12345:12345"
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - "/root/course/config.alloy:/etc/alloy/config.alloy"
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]
    restart: unless-stopped
