name: Run Continuous Integration
on:
  pull_request:
jobs:
  go-test:
    if: github.repository == 'grafana/killercoda'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: killercoda
      - uses: actions/setup-go@v5
        with:
          go-version-file: killercoda/tools/transformer/go.mod
      - run: go test ./...
        working-directory: killercoda/tools/transformer
