name: Regenerate tutorials
on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:
jobs:
  main:
    if: github.repository == 'grafana/killercoda'
    runs-on: ubuntu-latest
    steps:
      # Check out all the repositories that contain documentation sources from which we generate tutorials.
      - uses: actions/checkout@v4
        with:
          repository: grafana/loki
          path: loki
      - uses: actions/checkout@v4
        with:
          repository: grafana/grafana
          path: grafana
      - uses: actions/checkout@v4
        with:
            repository: grafana/alloy
            path: alloy
      - uses: actions/checkout@v4
        with:
            repository: grafana/tempo
            path: tempo
      - uses: actions/checkout@v4
        with:
          path: killercoda
      - uses: actions/setup-go@v5
        with:
          go-version-file: killercoda/tools/transformer/go.mod
      - run: go build ./
        working-directory: killercoda/tools/transformer
      - run: ./scripts/check-out-branch.bash
        shell: bash
        working-directory: killercoda
      # Run the transformer on all documentation sources.
      - run: >
          ./transformer
          "${GITHUB_WORKSPACE}/loki/docs/sources/get-started/quick-start.md"
          "${GITHUB_WORKSPACE}/killercoda/loki/loki-quickstart"
        working-directory: killercoda/tools/transformer
      - run: >
          ./transformer
          "${GITHUB_WORKSPACE}/loki/docs/sources/send-data/alloy/examples/alloy-kafka-logs.md"
          "${GITHUB_WORKSPACE}/killercoda/loki/alloy-kafka-logs"
        working-directory: killercoda/tools/transformer
      - run: >
          ./transformer
          "${GITHUB_WORKSPACE}/loki/docs/sources/send-data/alloy/examples/alloy-otel-logs.md"
          "${GITHUB_WORKSPACE}/killercoda/loki/alloy-otel-logs"
        working-directory: killercoda/tools/transformer
      - run: >
          ./transformer
          "${GITHUB_WORKSPACE}/grafana/docs/sources/tutorials/alerting-get-started/index.md"
          "${GITHUB_WORKSPACE}/killercoda/grafana/alerting-get-started"
        working-directory: killercoda/tools/transformer
      - run: >
          ./transformer
          "${GITHUB_WORKSPACE}/alloy/docs/sources/tutorials/send-logs-to-loki.md"
          "${GITHUB_WORKSPACE}/killercoda/alloy/send-logs-to-loki"
        working-directory: killercoda/tools/transformer
      - run: >
          ./transformer
          "${GITHUB_WORKSPACE}/grafana/docs/sources/tutorials/grafana-fundamentals/index.md"
          "${GITHUB_WORKSPACE}/killercoda/grafana/grafana-fundamentals"
        working-directory: killercoda/tools/transformer
      - run: >
          ./transformer
          "${GITHUB_WORKSPACE}/grafana/docs/sources/tutorials/create-alerts-with-logs/index.md"
          "${GITHUB_WORKSPACE}/killercoda/grafana/alerting-loki-logs"
        working-directory: killercoda/tools/transformer
      - run: >
          ./transformer
          "${GITHUB_WORKSPACE}/alloy/docs/sources/tutorials/send-metrics-to-prometheus.md"
          "${GITHUB_WORKSPACE}/killercoda/alloy/send-metrics-to-prometheus"
        working-directory: killercoda/tools/transformer
      - run: >
          ./transformer
          "${GITHUB_WORKSPACE}/tempo/docs/sources/tempo/getting-started/docker-example.md"
          "${GITHUB_WORKSPACE}/killercoda/tempo/quick-start"
        working-directory: killercoda/tools/transformer
      - run: ./scripts/manage-pr.bash
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        working-directory: killercoda
