name: Build and Release Transformer

permissions: {}

on:
  push:
    tags:
      - 'v*' # Trigger the workflow when a tag matching 'v*' is pushed
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-release:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows] # Target operating systems
        arch: [amd64, arm64] # Target architectures
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          cache: false
          go-version-file: killercoda/tools/transformer/go.mod

      - name: Build transformer
        working-directory: ./tools/transformer
        run: |
          mkdir -p ../../release
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ../../release/transformer-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: transformer-${{ matrix.os }}-${{ matrix.arch }}
          path: release/transformer-${{ matrix.os }}-${{ matrix.arch }}

  release:
    permissions:
      contents: write
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
